'use strict';

const fsp = require('fs/promises');
const path = require('path');

// Lazy dockerode so this module can be imported (e.g. by the proxy abstraction
// and unit tests) without the dependency present.
function getDocker() {
  return require('./docker').createDocker();
}

// Host path to the nginx conf.d that the acronym-nginx container mounts. Not
// hardcoded to the Linux '/etc/nginx/conf.d' — on a Windows host that resolves
// to C:\etc\nginx\conf.d and does not exist. Operators set NGINX_CONF_DIR.
const CONF_DIR = process.env.NGINX_CONF_DIR || '/etc/nginx/conf.d';

// Is the acronym-nginx reverse-proxy container running on this host?
async function nginxContainer() {
  const docker = getDocker();
  const containers = await docker.listContainers({
    filters: JSON.stringify({ name: ['acronym-nginx'] }),
  });
  return containers.length ? docker.getContainer(containers[0].Id) : null;
}

/**
 * Write an Nginx location config for a project.
 * Returns { published, reason } — never throws for a missing proxy/host path,
 * so a deploy on a host without nginx ends "running, unpublished" cleanly
 * instead of erroring on ENOENT.
 * @param {string} slug - Project slug
 * @param {number} port - Host port the container is bound to
 */
async function addProjectRoute(slug, port) {
  // No nginx container here → nothing would read the conf; skip cleanly.
  if (!(await nginxContainer())) return { published: false, reason: 'nginx_not_found' };

  const confContent = `# Auto-generated by acronym-deploy for project: ${slug}
location /${slug}/ {
    proxy_pass http://host.docker.internal:${port}/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_read_timeout 3600s;
}
`;

  const confPath = path.join(CONF_DIR, `${slug}.conf`);
  try {
    await fsp.mkdir(CONF_DIR, { recursive: true });
    await fsp.writeFile(confPath, confContent, 'utf8');
  } catch (err) {
    if (err.code === 'ENOENT') return { published: false, reason: 'conf_dir_missing' };
    throw err;
  }
  return { published: true };
}

/**
 * Remove the Nginx location config for a project.
 * @param {string} slug
 */
async function removeProjectRoute(slug) {
  const confPath = path.join(CONF_DIR, `${slug}.conf`);
  try {
    await fsp.unlink(confPath);
  } catch (err) {
    if (err.code !== 'ENOENT') {
      throw err;
    }
  }
}

/**
 * Reload Nginx by exec-ing `nginx -s reload` inside the acronym-nginx container.
 */
async function reloadNginx() {
  const docker = getDocker();
  const containers = await docker.listContainers({
    filters: JSON.stringify({ name: ['acronym-nginx'] }),
  });

  if (containers.length === 0) {
    console.warn('[nginx] acronym-nginx container not found, skipping reload');
    return;
  }

  const container = docker.getContainer(containers[0].Id);

  const exec = await container.exec({
    Cmd: ['nginx', '-s', 'reload'],
    AttachStdout: true,
    AttachStderr: true,
  });

  await new Promise((resolve, reject) => {
    exec.start({ hijack: false, stdin: false }, (err, stream) => {
      if (err) return reject(err);

      if (stream) {
        stream.on('data', () => {});
        stream.on('end', resolve);
        stream.on('error', reject);
      } else {
        resolve();
      }
    });
  });
}

module.exports = { addProjectRoute, removeProjectRoute, reloadNginx };
