'use strict';

const fsp = require('fs/promises');
const path = require('path');

// Lazy dockerode so this module can be imported (e.g. by the proxy abstraction
// and unit tests) without the dependency present.
function getDocker() {
  return require('./docker').createDocker();
}

const CONF_DIR = '/etc/nginx/conf.d';

/**
 * Write an Nginx location config for a project.
 * @param {string} slug - Project slug
 * @param {number} port - Host port the container is bound to
 */
async function addProjectRoute(slug, port) {
  const confContent = `# Auto-generated by acronym-deploy for project: ${slug}
location /${slug}/ {
    proxy_pass http://host.docker.internal:${port}/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_read_timeout 3600s;
}
`;

  const confPath = path.join(CONF_DIR, `${slug}.conf`);
  await fsp.writeFile(confPath, confContent, 'utf8');
}

/**
 * Remove the Nginx location config for a project.
 * @param {string} slug
 */
async function removeProjectRoute(slug) {
  const confPath = path.join(CONF_DIR, `${slug}.conf`);
  try {
    await fsp.unlink(confPath);
  } catch (err) {
    if (err.code !== 'ENOENT') {
      throw err;
    }
  }
}

/**
 * Reload Nginx by exec-ing `nginx -s reload` inside the acronym-nginx container.
 */
async function reloadNginx() {
  const docker = getDocker();
  const containers = await docker.listContainers({
    filters: JSON.stringify({ name: ['acronym-nginx'] }),
  });

  if (containers.length === 0) {
    console.warn('[nginx] acronym-nginx container not found, skipping reload');
    return;
  }

  const container = docker.getContainer(containers[0].Id);

  const exec = await container.exec({
    Cmd: ['nginx', '-s', 'reload'],
    AttachStdout: true,
    AttachStderr: true,
  });

  await new Promise((resolve, reject) => {
    exec.start({ hijack: false, stdin: false }, (err, stream) => {
      if (err) return reject(err);

      if (stream) {
        stream.on('data', () => {});
        stream.on('end', resolve);
        stream.on('error', reject);
      } else {
        resolve();
      }
    });
  });
}

module.exports = { addProjectRoute, removeProjectRoute, reloadNginx };
